# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\Documents\test_ui\ui\forgot_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgotPassword(object):
    def setupUi(self, ForgotPassword):
        ForgotPassword.setObjectName("ForgotPassword")
        ForgotPassword.resize(450, 851)
        self.centralwidget = QtWidgets.QWidget(ForgotPassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 801))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 181, 161))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 270, 221, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 380, 61, 41))
        self.label_4.setObjectName("label_4")
        self.errorMsgBox = QtWidgets.QLabel(self.centralwidget)
        self.errorMsgBox.setGeometry(QtCore.QRect(10, 460, 431, 31))
        self.errorMsgBox.setObjectName("errorMsgBox")
        self.sendCodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendCodeButton.setGeometry(QtCore.QRect(130, 560, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendCodeButton.setFont(font)
        self.sendCodeButton.setStyleSheet("* {\n"
"    color: black;\n"
"    background-color: lightblue;\n"
"    border: 1px solid lightblue;\n"
"    border-radius: 20px;\n"
"}")
        self.sendCodeButton.setObjectName("sendCodeButton")
        self.loginPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginPageButton.setGeometry(QtCore.QRect(100, 680, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.loginPageButton.setFont(font)
        self.loginPageButton.setStyleSheet("* { color: #0000ff }")
        self.loginPageButton.setAutoDefault(False)
        self.loginPageButton.setDefault(False)
        self.loginPageButton.setFlat(True)
        self.loginPageButton.setObjectName("loginPageButton")
        self.emailBox = QtWidgets.QLineEdit(self.centralwidget)
        self.emailBox.setGeometry(QtCore.QRect(170, 390, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailBox.setFont(font)
        self.emailBox.setObjectName("emailBox")
        ForgotPassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ForgotPassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        ForgotPassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ForgotPassword)
        self.statusbar.setObjectName("statusbar")
        ForgotPassword.setStatusBar(self.statusbar)

        self.retranslateUi(ForgotPassword)
        QtCore.QMetaObject.connectSlotsByName(ForgotPassword)

    def retranslateUi(self, ForgotPassword):
        _translate = QtCore.QCoreApplication.translate
        ForgotPassword.setWindowTitle(_translate("ForgotPassword", "MainWindow"))
        self.label.setText(_translate("ForgotPassword", "<html><head/><body><p><img src=\":/resources/resources/background.png\"/></p></body></html>"))
        self.label_2.setText(_translate("ForgotPassword", "<html><head/><body><p><img src=\":/resources/resources/icon.png\"/></p></body></html>"))
        self.label_3.setText(_translate("ForgotPassword", "<html><head/><body><p><span style=\" font-size:18pt;\">Forgot Password</span></p></body></html>"))
        self.label_4.setText(_translate("ForgotPassword", "<html><head/><body><p><span style=\" font-size:12pt;\">E-Mail:</span></p></body></html>"))
        self.errorMsgBox.setText(_translate("ForgotPassword", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.sendCodeButton.setText(_translate("ForgotPassword", "Send code"))
        self.loginPageButton.setText(_translate("ForgotPassword", "Login Page"))
        self.loginPageButton.setProperty("click", _translate("ForgotPassword", "ConfPageClicked"))
import resource_rc
