# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\Documents\test_ui\ui\output.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Output(object):
    def setupUi(self, Output):
        Output.setObjectName("Output")
        Output.resize(449, 851)
        self.centralwidget = QtWidgets.QWidget(Output)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, 0, 451, 801))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 181, 161))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 270, 81, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 380, 301, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 450, 351, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 580, 121, 121))
        self.label_6.setObjectName("label_6")
        Output.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Output)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 26))
        self.menubar.setObjectName("menubar")
        Output.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Output)
        self.statusbar.setObjectName("statusbar")
        Output.setStatusBar(self.statusbar)

        self.retranslateUi(Output)
        QtCore.QMetaObject.connectSlotsByName(Output)

    def retranslateUi(self, Output):
        _translate = QtCore.QCoreApplication.translate
        Output.setWindowTitle(_translate("Output", "MainWindow"))
        self.label.setText(_translate("Output", "<html><head/><body><p><img src=\":/resources/resources/background.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Output", "<html><head/><body><p><img src=\":/resources/resources/icon.png\"/></p></body></html>"))
        self.label_3.setText(_translate("Output", "<html><head/><body><p><span style=\" font-size:14pt;\">Output</span></p></body></html>"))
        self.label_4.setText(_translate("Output", "<html><head/><body><p><span style=\" font-size:12pt;\">&gt; user input e.g. What time is it?</span></p></body></html>"))
        self.label_5.setText(_translate("Output", "<html><head/><body><p><span style=\" font-size:12pt;\">Emilia\'s response e.g. Now is 10:57. &lt;</span></p></body></html>"))
        self.label_6.setText(_translate("Output", "<html><head/><body><p><img src=\":/resources/resources/speaking.png\"/></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Output = QtWidgets.QMainWindow()
    ui = Ui_Output()
    ui.setupUi(Output)
    Output.show()
    sys.exit(app.exec_())
